manipulator:
 kinematics_solver: ur_kinematics/UR10KinematicsPlugin
 kinematics_solver_search_resolution: 0.005
 kinematics_solver_timeout: 0.005
 kinematics_solver_attempts: 3
# http://answers.ros.org/question/194937/moveit-commander-not-able-to-find-a-motion-plan/ 
# manipulator:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
#   kinematics_solver_attempts: 3
